# Generated by Django 3.2.5 on 2021-08-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbquoats',
            old_name='name',
            new_name='princess_id',
        ),
    ]
