# Generated by Django 3.2.6 on 2021-08-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbcountry',
            old_name='country_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='dbprincess',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
