# Generated by Django 3.2.6 on 2021-08-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_dbprincess_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.dbprincess', to_field='country'),
        ),
        migrations.AlterField(
            model_name='dbprincess',
            name='country',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
