# Generated by Django 3.2.5 on 2021-08-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20210806_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbquoats',
            name='quoats',
        ),
        migrations.AddField(
            model_name='dbquoats',
            name='quoat_eng',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dbquoats',
            name='quoat_kor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dbprincess',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.dbcountry'),
        ),
    ]
