# Generated by Django 3.2.5 on 2021-08-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_auto_20210806_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_name', models.TextField(null=True)),
                ('clip_link', models.TextField(null=True)),
                ('princess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.dbprincess')),
            ],
        ),
    ]
