# Generated by Django 3.2.5 on 2021-08-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_dbclip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbsong',
            name='princess',
        ),
        migrations.DeleteModel(
            name='DBScene',
        ),
        migrations.DeleteModel(
            name='DBSong',
        ),
    ]
