# Generated by Django 3.2.5 on 2021-08-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_content_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
